### ISSUE TITLE
Doesn't encrypt YAML array values

### ISSUE THREAD

**Issue by wflanagan** [MiguelSavignano/node-credentials#56]
i tried to use this on a project. It wouldn't encrypt an array values in this structure:

```yaml
---
proxies:
  proxy_service_1:
     config:
        key1: value
        key2: value
     data: 
        - item 1
        - item 2
        - item 3
 ```
In my case, the data array attributes in this structure were NOT encrypted.
